export const CATEGORIES_GET_REQUEST = 'CATEGORIES_GET_REQUEST';
export const CATEGORIES_GET_SUCCESS = 'CATEGORIES_GET_SUCCESS';
export const CATEGORIES_GET_FAILURE = 'CATEGORIES_GET_FAILURE';

export const POSTS_GET_REQUEST = 'POSTS_GET_REQUEST';
export const POSTS_GET_SUCCESS = 'POSTS_GET_SUCCESS';
export const POSTS_GET_FAILURE = 'POSTS_GET_FAILURE';

export const SORT_CHANGE_SUCCESS = 'SORT_CHANGE_SUCCESS';
export const CATEGORY_CHANGE_SUCCESS = 'CATEGORY_CHANGE_SUCCESS';
export const CATEGORY_CHANGE_FAILURE = 'CATEGORY_CHANGE_FAILURE';

export const POST_ADD_REQUEST = 'POST_ADD_REQUEST';
export const POST_ADD_SUCCESS = 'POST_ADD_SUCCESS';
export const POST_ADD_FAILURE = 'POST_ADD_FAILURE';

export const POST_EDIT_REQUEST = 'POST_EDIT_REQUEST';
export const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS';
export const POST_EDIT_FAILURE = 'POST_EDIT_FAILURE';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAILURE = 'POST_DELETE_FAILURE';

export const POST_VOTE_REQUEST = 'POST_VOTE_REQUEST';
export const POST_VOTE_FAILURE = 'POST_VOTE_FAILURE';
export const POST_VOTE_SUCCESS = 'POST_VOTE_SUCCESS';

export const COMMENTS_GET_REQUEST = 'COMMENTS_GET_REQUEST';
export const COMMENTS_GET_FAILURE = 'COMMENTS_GET_FAILURE';
export const COMMENTS_GET_SUCCESS = 'COMMENTS_GET_SUCCESS';

export const POST_GET_REQUEST = 'POST_GET_REQUEST';
export const POST_GET_SUCCESS = 'POST_GET_SUCCESS';
export const POST_GET_FAILURE = 'POST_GET_FAILURE';

export const COMMENT_ADD_REQUEST = 'COMMENT_ADD_REQUEST';
export const COMMENT_ADD_SUCCESS = 'COMMENT_ADD_SUCCESS';
export const COMMENT_ADD_FAILURE = 'COMMENT_ADD_FAILURE';

export const COMMENT_VOTE_REQUEST = 'COMMENT_VOTE_REQUEST';
export const COMMENT_VOTE_SUCCESS = 'COMMENT_VOTE_SUCCESS';
export const COMMENT_VOTE_FAILURE = 'COMMENT_VOTE_FAILURE';

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAILURE = 'COMMENT_DELETE_FAILURE';

export const COMMENT_EDIT_REQUEST = 'COMMENT_EDIT_REQUEST';
export const COMMENT_EDIT_SUCCESS = 'COMMENT_EDIT_SUCCESS';
export const COMMENT_EDIT_FAILURE = 'COMMENT_EDIT_FAILURE';
